import { PayloadAction, createSlice } from '@reduxjs/toolkit'

const initialState = {
	catalog: [
		{
			id: 'bigComplex',
			items: [
				{
					id: 'naturalWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'naturalWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
			],
		},
		{
			id: 'smallComplex',
			items: [
				{
					id: 'naturalWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'naturalWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
			],
		},
		{
			id: 'bowls',
			items: [
				{
					id: 'naturalWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'naturalWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
			],
		},
		{
			id: 'toys',
			items: [
				{
					id: 'naturalWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'naturalWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
			],
		},
		{
			id: 'sparePart',
			items: [
				{
					id: 'naturalWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item1.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
									'/pictures/complex/item1.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item2.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
									'/pictures/complex/item2.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelWhite',
					cabel: 'input-roke-white',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item3.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
									'/pictures/complex/item3.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'naturalWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-natural',
					cabelTitle: 'Натуральный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item4.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
									'/pictures/complex/item4.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'lightWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-light',
					cabelTitle: 'Белёный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item5.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
									'/pictures/complex/item5.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
				{
					id: 'darkWhite-cabelBlack',
					cabel: 'input-roke-black',
					material: 'input-oak-dark',
					cabelTitle: 'Тёмный дуб',
					materialTitle: 'Белый канат',
					items: [
						{
							itemId: 'first',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'second',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
						{
							itemId: 'third',
							count: 0,
							src: '/pictures/complex/item6.jpg',
							price: 19.999,
							priceDiscount: 20.999,
							title: 'Когтеточка Бай',
							characteristics: [{ title: 'Дерево', text: 'Дуб' }],
							info: {
								src: [
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
									'/pictures/complex/item6.jpg',
								],
								description: [
									'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
								],
							},
						},
					],
				},
			],
		},
	],
	categoriesArray: [
		{
			id: 'bigComplex',
			content: 'Большие комплексы',
		},
		{
			id: 'smallComplex',
			content: 'Малые комплексы',
		},
		{
			id: 'bowls',
			content: 'Миски',
		},
		{
			id: 'toys',
			content: 'Игрушки',
		},
		{
			id: 'sparePart',
			content: 'Запчасти',
		},
	],
	materialArray: [
		{
			src: '/public/pictures/combination/inputs/oak-natural.png',
			id: 'input-oak-natural',
		},
		{
			src: '/public/pictures/combination/inputs/oak-light.png',
			id: 'input-oak-light',
		},
		{
			src: '/public/pictures/combination/inputs/oak-dark.png',
			id: 'input-oak-dark',
		},
	],
	cabelArray: [
		{
			src: '/public/pictures/combination/inputs/rope-white.png',
			id: 'input-roke-white',
		},
		{
			src: '/public/pictures/combination/inputs/rope-black.png',
			id: 'input-roke-black',
		},
	],
	activeCategories: 'bigComplex',
	activeMaterial: 'input-oak-natural',
	activeCabel: 'input-roke-white',
}
export const CatalogSlice = createSlice({
	name: 'calatog',
	initialState,
	reducers: {
		changeActiveCategories: (state, action: PayloadAction<string>) => {
			state.activeCategories = action.payload
		},
		changeCatalogActiveCabel: (state, action: PayloadAction<string>) => {
			state.activeCabel = action.payload
		},
		changeCatalogActiveMaterial: (state, action: PayloadAction<string>) => {
			state.activeMaterial = action.payload
		},
	},
})

export default CatalogSlice.reducer
export const {
	changeActiveCategories,
	changeCatalogActiveCabel,
	changeCatalogActiveMaterial,
} = CatalogSlice.actions
